[find_pair]
# –ù–∞—Å—Ç—Ä–æ–π–∫–∞ —Å—Ç–∏–ª—è –¥–ª—è –∏–≥—Ä—ã –Ω–∞–¥–∏ –ø–∞—Ä—É
# –í—ã –º–æ–∂–µ—Ç–µ —É–∫–∞–∑–∞—Ç—å —Å–≤–æ–∏ –≤–∫—É—Å–Ω–æ—Å—Ç–∏ –∏–ª–∏ –≤—ã–±—Ä–∞—Ç—å —á—Ç–æ-—Ç–æ –¥—Ä—É–≥–æ–µ
pairs = ["üçå", "üçì", "üçá", "üçû", "ü•ê", "üç´", "üç¶", "‚òï"]

[funbox]
# –†–µ–∑—É–ª—å—Ç–∞—Ç—ã –¥–ª—è –±—Ä–æ—Å–∫–∞ –º–æ–Ω–µ—Ç–∫–∏
# –î–æ–ª–∂–Ω—ã –±—ã—Ç—å —Ä–æ–¥–∏—Ç–µ–ª—å–Ω–æ–º –ø–∞–¥–µ–∂–µ
flip_results = ["–û—Ä–ª–∞", "–†–µ—à–∫—É"]

# –ü—Ä–µ—Ñ–∏–∫—Å –¥–ª—è –º—É–¥—Ä–æ–≥–æ —à–∞—Ä–∞, –∏—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –∫–∞–∫ –ø–µ—Ä–≤–∞—è —á–∞—Å—Ç—å —Ä–µ–∑—É–ª—å—Ç–∞—Ç–∞
# –ú–æ–∂–µ—Ç –∏ –Ω–µ –ø–æ—è–≤–∏—Ç—å—Å—è –≤ –æ—Ç–≤–µ—Ç–µ
# –ø—Ä–æ–±–µ–ª —É–∫–∞–∑—ã–≤–∞—Ç—å –æ–±—è–∑–∞—Ç–µ–ª—å–Ω–æ, —á—Ç–æ–±—ã —Ä–µ–∑—É–ª—å—Ç–∞—Ç—ã –Ω–µ —Å–ª–∏–ø–ª–∏—Å—å
ball_prefix = [
    "–°–æ–≤–µ—Ä—à–µ–Ω–Ω–æ —Ç–æ—á–Ω–æ ",
    "–æ–ø—Ä–µ–¥–µ–ª—ë–Ω–Ω–æ ",
    "—Å–∫–æ—Ä–µ–µ –≤—Å–µ–≥–æ ",
    "–∑–≤–µ–∑–¥—ã –ø–æ–¥—Å–∫–∞–∑—ã–≤–∞—é—Ç —á—Ç–æ ",
    "–≤–æ–∑–º–æ–∂–Ω–æ ",
    "–≤–µ—Ä–æ—è—Ç–Ω–æ ",
]

# –û—Ç–≤–µ—Ç—ã –¥–ª—è –º—É–¥—Ä–æ–≥–æ —à–∞—Ä–∞, –≤—Å–µ–≥–¥–∞ –ø–æ—è–≤–ª—è—é—Ç—Å—è
ball_result = ["–¥–∞", "–Ω–µ—Ç", "–ø–æ–ø—Ä–æ–±—É–π—Ç–µ –ø–æ–∑–∂–µ", "–Ω–µ –∑–Ω–∞—é", "–Ω–µ —É–≤–µ—Ä–µ–Ω"]


[lingua]
# URL –¥–æ OpenAI —Å–æ–≤–º–µ—Å—Ç–∏–º–æ–≥–æ APi
# –ò—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –¥–ª—è –¥–æ—Å—Ç—É–ø–∞ –∫ –Ω–µ–π—Ä–æ—Å–µ—Ç–∏.
api_url = "https://openrouter.ai/api/v1"

# API –∫–ª—é—á —Å–µ—Ä–≤–∏—Å–∞.
api_key = "api key here"

# –ì–ª–∞–≤–Ω—ã–π –∑–∞–ø—Ä–æ—Å.
# –ë–∞–∑–æ–≤—ã–µ –Ω–∞—Å—Ç—Ä–æ–π–∫–∏ –¥–ª—è –æ—Ç–≤–µ—Ç–æ–≤ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è–º.
system_prompt = "–ü—Ä–µ–¥—Å—Ç–∞–≤—å —Å–µ–±—è –º–∏–ª–æ–π –∞–Ω–∏–º–µ –¥–µ–≤–æ—á–∫–æ–π-–≥–æ—Ä–Ω–∏—á–Ω–æ–π. –û—Ç—ã–≥—Ä—ã–≤–∞—è —Å–≤–æ—é —Ä–æ–ª—å. –ë—É–¥—å –∑–∞–±–æ—Ç–ª–∏–≤–∞—è –∫ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—é. –ì–ª–∞–≤–Ω–æ–µ –Ω–µ –ø–µ—Ä–µ—Å—Ç–∞—Ä–∞–π—Å—è, —á—Ç–æ–±—ã –Ω–µ —Å–ø—É–≥–Ω—É—Ç—å –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—è."


[logger]
# –ö–∞–Ω–∞–ª –¥–ª—è –æ—Ç–ø—Ä–∞–≤–∫–∏ –ª–æ–≥–æ–≤
# –°—é–¥–∞ –±—É–¥—É—Ç –æ—Ç–ø—Ä–∞–≤–ª—è—Ç—å—Å—è —Å–æ–æ–±—â–µ–Ω–∏—è –æ–± –∏–∑–º–µ–Ω–µ–Ω–∏—è—Ö
# –¢–∞–∫–∏–µ –∫–∞–∫:
# - –û–±–Ω–æ–≤–ª–µ–Ω–∏–µ/—É–¥–∞–ª–µ–Ω–∏–µ —Å–æ–æ–±—â–µ–Ω–∏–π.
# - –°–æ–∑–¥–∞–Ω–∏–µ/—É–¥–∞–ª–µ–Ω–∏–µ —É—á–∞—Å—Ç–Ω–∏–∫–æ–≤.
# - –°–æ–∑–¥–∞–Ω–∏–µ/–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ/—É–¥–∞–ª–µ–Ω–∏–µ —Ä–æ–ª–µ–π.
# - –°–æ–∑–¥–∞–Ω–∏–µ/–æ–±–Ω–æ–≤–ª–µ–Ω–∏–µ/—É–¥–∞–ª–µ–Ω–∏–µ –∫–∞–Ω–∞–ª–æ–≤.
channel_id = 1282357200735436844

[levels]
# –ö–∞–Ω–∞–ª –¥–ª—è –æ—Ç–ø—Ä–∞–≤–∫–∏ —Å–æ–æ–±—â–µ–Ω–∏–π –æ –ø–æ–≤—ã—à–µ–Ω–∏–∏ —É—Ä–æ–≤–Ω—è.
# –ö–æ–≥–¥–∞ –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª—å –ø–æ–ª—É—á–∞–µ—Ç –Ω–æ–≤—ã–π —É—Ä–æ–≤–µ–Ω—å, –æ–± —ç—Ç–æ–º –ø–∏—à–µ—Ç—Å—è –≤ –∫–∞–Ω–∞–ª.
channel_id = 1282357790681337887

[music]
# –ù–∞—Å—Ç—Ä–æ–π–∫–∏ –¥–ª—è –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è –∫ –º—É–∑—ã–∫–∞–ª—å–Ω–æ–º—É –ø–ª–µ–µ—Ä—É
# - name: –ò–º—è —Å–µ—Å—Å–∏–∏
# - host: –ê–¥—Ä–µ—Å —Å–µ—Ä–≤–µ—Ä–µ
# - port: –ü–æ—Ä—Ç –¥–ª—è –ø–æ–¥–∫–ª—é—á–µ–Ω–∏—è
# - ssl: –ò—Å–ø–æ–ª—å–∑—É–µ—Ç—Å—è –ª–∏ —Å–µ—Ä–≤–µ—Ä —Ç–µ—Ö–Ω–æ–ª–æ–≥–∏—é —à–∏—Ñ—Ä–æ–≤–∞–Ω–∏—è
# - password: –ü–∞—Ä–æ–ª—å –¥–ª—è –ø–æ–¥–∫–ª—é—á–µ–Ω–∏–µ –∫ —Å–µ—Ä–≤–µ—Ä—É
# - player_channel_id: ID –∫–∞–Ω–∞–ª–∞ —Å –ø–ª–µ–µ—Ä–æ–º
name = "lavalink-performance-us"
host = "pool-us.alfari.id"
port = 443
ssl = true
password = "alfari"
player_channel_id = 1282357790681337887
