[tool.poetry]
name = "chioricord"
version = "0.4"
description = "Nulti-functional discord bot for your server"
authors = ["Milinuri Nirvalen <pentergust@mail.ru>"]
license = "GPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
loguru = "^0.7.2"
aiosqlite = "^0.20.0"
python-dotenv = "^1.0.1"
aiohttp = "^3.9.3"
nest-asyncio = "^1.6.0"

hikari = "^2.0.0.dev126"
hikari-arc = "^1.3.4"
hikari-miru = "^4.1.1"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.4"
isort = "^5.13.2"
icecream = "^2.1.3"

[tool.ruff]
line-length = 80
indent-width = 4

target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "D", "N", "PL"]
ignore = ["D407", "D107", "D213", "D203"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
